# Generated by Django 4.2.1 on 2025-08-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unique_slug', models.SlugField(max_length=100, unique=True)),
                ('full_domain', models.CharField(max_length=255, unique=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=20, null=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('np', 'Nepali')], default='en', max_length=10)),
                ('time_zone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
