# Generated by Django 4.2.1 on 2025-08-06 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipality', '0001_initial'),
        ('QRAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('approx_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'QR Analytics',
            },
        ),
        migrations.CreateModel(
            name='QRScanSummary',
            fields=[
                ('qr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scan_summary', serialize=False, to='QRAPP.qr')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('total_scans', models.PositiveIntegerField(default=0)),
                ('unique_ip_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QR Scan Summary',
                'verbose_name_plural': 'QR Scan Summaries',
            },
        ),
        migrations.AlterModelOptions(
            name='qr',
            options={'verbose_name': 'QR Code', 'verbose_name_plural': 'QR Codes'},
        ),
        migrations.RemoveField(
            model_name='qr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='last_scanned',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='total_scans',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='unique_ip_count',
        ),
        migrations.AddField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='entity_type',
            field=models.CharField(choices=[('place', 'Place'), ('event', 'Event'), ('feedback', 'Feedback'), ('business', 'Business Listing'), ('municipality', 'Municipality Profile')], default='feedback', max_length=50),
        ),
        migrations.AlterField(
            model_name='qr',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='municipality.municipality'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qr',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='qr',
            index=models.Index(fields=['entity_type', 'entity_id'], name='QRAPP_qr_entity__dcaefe_idx'),
        ),
        migrations.AddField(
            model_name='qranalytics',
            name='qr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_analytics', to='QRAPP.qr'),
        ),
        migrations.AddIndex(
            model_name='qranalytics',
            index=models.Index(fields=['qr'], name='QRAPP_qrana_qr_id_8466b2_idx'),
        ),
        migrations.AddIndex(
            model_name='qranalytics',
            index=models.Index(fields=['entity_type', 'entity_id'], name='QRAPP_qrana_entity__c11270_idx'),
        ),
    ]
