version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 7000
    ports:
      - 7000:7000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A admin_module worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A admin_module beat --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7
    ports:
      - 6380:6379 # Changed host port from 6379 to 6380

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    depends_on:
      - db

volumes:
  mysql_data:
  static_volume:
