# Generated by Django 4.2.1 on 2025-07-30 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_event_created_by_event_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultiLingiualEvent',
            new_name='MultiLingualEvent',
        ),
    ]
