# Generated by Django 4.2.1 on 2025-07-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_eventpublicinteraction_bookmark_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
