# Generated by Django 4.2.1 on 2025-07-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_multilingiualevent_multilingualevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='organizerinfo',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organizerinfo',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='organizerinfo',
            name='website',
        ),
        migrations.AddField(
            model_name='event',
            name='booking_rsvp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_type',
            field=models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-in'), ('email', 'Email'), ('phone', 'Phone')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='short_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='target_audience',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.CharField(choices=[('free', 'Free'), ('fixed', 'Fixed'), ('donation', 'Donation'), ('tiered', 'Tiered')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='Max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
