# Generated by Django 4.2.1 on 2025-07-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventlocation_zip_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiLingualEvent',
        ),
    ]
