# Generated by Django 4.2.1 on 2025-07-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('traveler', 'Traveler'), ('company', 'Travel Company'), ('hotel_owner', 'Hotel Owner'), ('guide', 'Guide'), ('admin', 'Admin'), ('manager', 'Manager'), ('seo', 'SEO Team'), ('content', 'Content Writer'), ('support', 'Support Agent')], default='traveler', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('married', 'Married'), ('unmarried', 'Unmarried')], default='married', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('preferred_pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('guide', 'Guide'), ('hotel', 'Hotel')], default='customer', max_length=20)),
                ('profile_type', models.CharField(choices=[('guest', 'Guest'), ('basic', 'Basic'), ('verified', 'Verified')], default='guest', max_length=20)),
                ('id_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('kyc_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('preferred_payment_type', models.CharField(choices=[('fonepay', 'FonePay'), ('card', 'Card'), ('wallet', 'Wallet'), ('cash', 'Cash')], default='fonepay', max_length=20)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('price_sensitivity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
