# Generated by Django 4.2.1 on 2025-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_adminuser_user_municipality_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
