# Generated by Django 4.2.1 on 2025-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='approx_location',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='qr',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='total_scans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qr',
            name='unique_ip_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qranalytics',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qranalytics',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='entity_type',
            field=models.CharField(choices=[('place', 'Place'), ('event', 'Event'), ('business', 'Business Listing'), ('municipality', 'Municipality Profile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr_code_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='QRScanSummary',
        ),
    ]
