# Generated by Django 4.2.1 on 2025-07-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_coverage', models.CharField(choices=[('Local', 'Local area'), ('Municipality', 'Full municipality'), ('District', 'Entire district')], default='Local', max_length=100)),
                ('pricing_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Range', 'Range')], default='Fixed', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10)),
                ('slug', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('business', models.CharField(choices=[('Hotel', 'Hotel'), ('TravelAgency', 'Travel Agency'), ('Restaurant', 'Restaurant'), ('TaxiService', 'Taxi Service'), ('LocalProduct', 'Local Product'), ('Rental', 'Rental'), ('GuideAgency', 'Guide Agency')], max_length=50)),
                ('booking', models.CharField(choices=[('Phone', 'phone'), ('Email', 'email'), ('Whatsapp', 'whatsapp'), ('Instagram', 'instagram'), ('In_Person_website', 'in_person_website')], max_length=50)),
                ('short_description', models.CharField(max_length=50)),
                ('full_description', models.TextField()),
                ('Established_Date', models.DateTimeField(blank=True, null=True)),
                ('reg_no', models.CharField(max_length=255, unique=True)),
                ('overview', models.TextField()),
                ('history', models.TextField()),
                ('values', models.TextField()),
                ('specialities', models.JSONField(default=list)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_offer', models.JSONField(blank=True, default=list)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_notes', models.TextField(blank=True)),
                ('extra_travel_fee_notes', models.TextField(blank=True)),
                ('keyword', models.CharField(choices=[('family_friendly', 'Family-Friendly'), ('budget', 'Budget'), ('luxury', 'Luxury'), ('home_delivery', 'Home Delivery')], max_length=50)),
                ('authorized_person', models.CharField(max_length=255)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('open_days', models.CharField(blank=True, help_text='e.g., Mon-Fri, Everyday, Sat-Sun', max_length=100)),
                ('cover_image', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
