# Generated by Django 4.2.1 on 2025-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='service_offer',
            field=models.JSONField(default=list),
        ),
    ]
