# Generated by Django 4.2.1 on 2025-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_service_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='service_offer',
        ),
        migrations.AlterField(
            model_name='business',
            name='specialities',
            field=models.JSONField(default=list),
        ),
    ]
