# Generated by Django 4.2.1 on 2025-07-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='business',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='business',
            name='tripadvisor_link',
        ),
    ]
