# Generated by Django 4.2.1 on 2025-07-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_service_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='service_offer',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
