# Generated by Django 4.2.1 on 2025-07-28 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_business_service_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccessibilitypreference',
            name='user',
        ),
        migrations.RenameField(
            model_name='businessmedia',
            old_name='brochure_pdf',
            new_name='media_url',
        ),
        migrations.RemoveField(
            model_name='businessmedia',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='businessmedia',
            name='gallery_images',
        ),
        migrations.RemoveField(
            model_name='businessmedia',
            name='video_embed_url',
        ),
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessmedia',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='business.business'),
        ),
        migrations.DeleteModel(
            name='GalleryMedia',
        ),
        migrations.DeleteModel(
            name='UserAccessibilityPreference',
        ),
    ]
