# Generated by Django 4.2.1 on 2025-08-04 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='description_nepali',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('feedback', 'Feedback')], default='complaint', help_text='Type of feedback', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='map_pin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='map_pin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='spam_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='title_nepali',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='tracking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedbackcategory',
            name='name_nepali',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='public_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='response_type',
            field=models.CharField(choices=[('public', 'Public Response'), ('private', 'Private Response'), ('internal', 'Internal Note')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email for the location', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the location', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='total_scans',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='unique_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qrlocation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbackstatus',
            name='name',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='QRAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('scan_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipality.municipality')),
                ('qr_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='feedback.qrlocation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
