# Generated by Django 4.2.1 on 2025-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
