# Generated by Django 4.2.1 on 2025-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_attachment_file_size_attachment_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('feedback', 'Feedback')], default='complaint', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='target_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
