# Generated by Django 4.2.1 on 2025-08-06 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_qr_latitude_qr_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QR',
        ),
    ]
