# Generated by Django 4.2.1 on 2025-08-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_feedback_type_alter_qrlocation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='description_nepali',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='title_nepali',
        ),
    ]
