# Generated by Django 4.2.1 on 2025-08-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_remove_feedback_description_nepali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='qrlocation',
            name='qr_code_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
