# Generated by Django 4.2.1 on 2025-08-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        ('feedback', '0005_remove_attachment_file_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='FeedbackMedia',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='qr_location',
        ),
        migrations.RemoveField(
            model_name='qranalytics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qrlocation',
            name='municipality',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='map_pin_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='map_pin_lng',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='qr_location',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='spam_flag',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='submitted_phone',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ward',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('inquiry', 'Inquiry'), ('feedback', 'Feedback')], default='feedback', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='municipality.municipality'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='FeedbackCategory',
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
        migrations.DeleteModel(
            name='FeedbackStatus',
        ),
        migrations.DeleteModel(
            name='QRAnalytics',
        ),
        migrations.DeleteModel(
            name='QRLocation',
        ),
    ]
