# Generated by Django 4.2.1 on 2025-08-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_rename_attachment_feedbackmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='is_public',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='ip_address',
        ),
    ]
