# Generated by Django 4.2.1 on 2025-07-31 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscover', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('vr_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('timeline', models.TextField(blank=True)),
                ('key_attractions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('popular_season', models.CharField(blank=True, max_length=100)),
                ('accessibility', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('entry_fee_local', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('entry_fee_foreign', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('guide_service', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('toilets', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('font_size_toggle', models.BooleanField(default=False)),
                ('contrast_mode', models.BooleanField(default=False)),
                ('screen_reader_friendly', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_image', models.URLField(blank=True)),
                ('approval_status', models.CharField(default='draft', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='municipality.municipality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
