# Generated by Django 4.2.1 on 2025-07-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_places', to='municipality.municipality'),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='slug',
            field=models.SlugField(),
        ),
    ]
