# Generated by Django 4.2.1 on 2025-07-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_initial'),
        ('tourism', '0002_touristplace_municipality_alter_touristplace_slug'),
    ]

    operations = [
    ]
