# Generated by Django 4.2.1 on 2025-07-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipality', '0001_initial'),
        ('tourism', '0003_merge_20250728_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='municipality.municipality'),
        ),
    ]
