# Generated by Django 4.2.1 on 2025-08-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_unpublish_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('body', models.TextField(blank=True)),
                ('banner_image', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('default', 'Default'), ('landing', 'Landing Page'), ('article', 'Article'), ('contact', 'Contact'), ('about', 'About')], default='default', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='municipality.municipality')),
                ('translated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=255)),
                ('new_slug', models.SlugField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='cms.page')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('cta', 'Call to Action'), ('gallery', 'Gallery'), ('embed', 'Embed'), ('contact_form', 'Contact Form')], default='text', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PagePreviewToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_tokens', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.TextField(blank=True)),
                ('robots_directive', models.CharField(blank=True, default='index, follow', max_length=50)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='page_media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.page')),
            ],
            options={
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['page', 'version_number'], name='cms_pagever_page_id_d8f879_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(fields=('page', 'version_number'), name='unique_page_version'),
        ),
        migrations.AddIndex(
            model_name='pageslughistory',
            index=models.Index(fields=['old_slug', 'page'], name='cms_pageslu_old_slu_7b28cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pageslughistory',
            index=models.Index(fields=['new_slug', 'page', 'changed_at'], name='cms_pageslu_new_slu_2763c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageslughistory',
            constraint=models.UniqueConstraint(fields=('old_slug', 'page'), name='unique_old_slug_page'),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['page', 'position'], name='cms_pagesec_page_id_6e7a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemedia',
            index=models.Index(fields=['page', 'is_featured'], name='cms_pagemed_page_id_79fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemedia',
            index=models.Index(fields=['is_featured'], name='cms_pagemed_is_feat_063e42_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'slug', 'language_code'], name='cms_page_municip_e4bf6f_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'status', 'published_at'], name='cms_page_municip_bbc008_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'language_code'], name='cms_page_municip_5d517a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'scheduled_publish_at'], name='cms_page_municip_077d62_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'scheduled_unpublish_at'], name='cms_page_municip_b6f457_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'is_featured'], name='cms_page_municip_d3dbe6_idx'),
        ),
    ]
