# Generated by Django 4.2.1 on 2025-08-20 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='scheduled_unpublish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageversion',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PagePreviewToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_tokens', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=255)),
                ('new_slug', models.SlugField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='cms.page')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['old_slug', 'page'], name='cms_pageslu_old_slu_7b28cd_idx'), models.Index(fields=['new_slug', 'page', 'changed_at'], name='cms_pageslu_new_slu_2763c8_idx')],
            },
        ),
    ]
