# Generated by Django 4.2.1 on 2025-08-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_scheduled_publish_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pageversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='page_media/'),
        ),
        migrations.AddField(
            model_name='pagemedia',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagemedia',
            name='media_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'scheduled_publish_at'], name='cms_page_municip_077d62_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'scheduled_unpublish_at'], name='cms_page_municip_b6f457_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['municipality', 'is_featured'], name='cms_page_municip_d3dbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemedia',
            index=models.Index(fields=['page', 'is_featured'], name='cms_pagemed_page_id_79fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='pagemedia',
            index=models.Index(fields=['is_featured'], name='cms_pagemed_is_feat_063e42_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('municipality', 'slug', 'language_code'), name='unique_page_slug_active'),
        ),
        migrations.AddConstraint(
            model_name='pagemedia',
            constraint=models.CheckConstraint(check=models.Q(('file__isnull', False), models.Q(('url', ''), _negated=True), models.Q(('media_url', ''), _negated=True), _connector='OR'), name='page_media_requires_one_source'),
        ),
        migrations.AddConstraint(
            model_name='pageslughistory',
            constraint=models.UniqueConstraint(fields=('old_slug', 'page'), name='unique_old_slug_page'),
        ),
        migrations.AddConstraint(
            model_name='pageversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('page', 'version_number'), name='unique_page_version_active'),
        ),
    ]
